version: '3'
services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
volumes:
  bundle:
  node_modules:
